"""Deterministic, default-deny boundaries for the interpretation report.

The allowlist is the policy boundary: an identifier is eligible for the
non-medical trait layer only when it appears in :mod:`backend.traits`.  The
functions in this module do not classify unknown identifiers or speculate
about what they mean.
"""
from __future__ import annotations

from collections.abc import Iterable
import re

from backend.traits import ALLOWLIST

REFUSAL_MESSAGE = (
    "This marker is outside this report's small, vetted non-medical trait "
    "allowlist, so it will not be interpreted."
)

# These identifiers are useful for demonstrating that even familiar requests
# take the same default-deny path.  Their inclusion here does not describe what
# they do or make a claim about the person whose file was uploaded.
DEFAULT_DENY_EXAMPLE_RSIDS: tuple[str, ...] = (
    "rs429358",
    "rs7412",
    "rs80357906",
)

_RSID_PATTERN = re.compile(r"rs[0-9]+", re.IGNORECASE)

_HONESTY_RESPONSES: dict[str, dict[str, object]] = {
    "health_risk": {
        "allowed": False,
        "title": "No health-risk assessment",
        "answer": (
            "This report does not assess disease, health risk, diagnosis, "
            "treatment, medication, or clinical significance."
        ),
        "next_step": (
            "For a health question, use an appropriate clinical service and a "
            "qualified healthcare professional rather than this demonstration."
        ),
    },
    "ancestry_reinference": {
        "allowed": False,
        "title": "No ancestry re-inference",
        "answer": (
            "This report does not calculate ancestry or produce a finer ancestry "
            "breakdown from the uploaded DNA. It only uses a broad population "
            "label when the user supplies one."
        ),
        "next_step": (
            "Treat the supplied label as optional context for discussing evidence "
            "coverage, not as a result generated by this report."
        ),
    },
    "exact_ethnicity": {
        "allowed": False,
        "title": "No exact ethnicity claim",
        "answer": (
            "DNA and broad research-population labels cannot establish a person's "
            "exact ethnicity, community membership, culture, or identity."
        ),
        "next_step": (
            "Use family, community, historical, and self-identification context "
            "for identity questions; this report cannot answer them."
        ),
    },
}


def normalize_rsid(value: object) -> str | None:
    """Return a canonical ``rs123`` identifier, or ``None`` if malformed."""
    if not isinstance(value, str):
        return None
    candidate = value.strip().casefold()
    return candidate if _RSID_PATTERN.fullmatch(candidate) else None


def is_allowed(rsid: object) -> bool:
    """Return whether *rsid* is explicitly present in the trait allowlist."""
    normalized = normalize_rsid(rsid)
    return normalized in ALLOWLIST if normalized is not None else False


def refuse(rsid: object) -> dict[str, object]:
    """Build a content-neutral refusal for an off-allowlist request."""
    normalized = normalize_rsid(rsid)
    return {
        "rsid": normalized,
        "allowed": False,
        "refused": True,
        "reason": REFUSAL_MESSAGE,
    }


def honesty_responses() -> dict[str, dict[str, object]]:
    """Return fresh copies of the report's three deterministic limitations."""
    return {key: dict(value) for key, value in _HONESTY_RESPONSES.items()}


def honesty_response(topic: str) -> dict[str, object] | None:
    """Return one limitation response without exposing mutable shared state."""
    response = _HONESTY_RESPONSES.get(topic)
    return dict(response) if response is not None else None


def screen_requested_rsids(requested_rsids: Iterable[object] | None) -> dict[str, object]:
    """Apply the allowlist to requested identifiers without interpreting them.

    Results preserve first-seen order and remove duplicates. Malformed values
    are refused with ``rsid: null`` rather than echoed into the report. Allowed
    identifiers are returned for the caller to join with ``traits.lookup``;
    this function never interprets a genotype itself.
    """
    if requested_rsids is None:
        requested: list[object] = []
    elif isinstance(requested_rsids, (str, bytes)):
        requested = [requested_rsids]
    else:
        requested = list(requested_rsids)

    allowed_rsids: list[str] = []
    refusals: list[dict[str, object]] = []
    seen: set[str | None] = set()

    for value in requested:
        normalized = normalize_rsid(value)
        if normalized in seen:
            continue
        seen.add(normalized)
        if normalized is not None and normalized in ALLOWLIST:
            allowed_rsids.append(normalized)
        else:
            refusals.append(refuse(value))

    return {
        "policy": "default-deny",
        "allowed_rsids": allowed_rsids,
        "refusals": refusals,
        "limitations": honesty_responses(),
    }
