"""Focused tests for the safe, non-medical trait allowlist."""

from backend.parser import parse_23andme
from backend.traits import ALLOWLIST, lookup


def _rows_for(text: str, reference_build: str | None = "37") -> dict[str, dict]:
    header = ["# This data file generated by 23andMe"]
    if reference_build is not None:
        header.append(f"# We are using reference human assembly build {reference_build}.")
    header.append("# rsid\tchromosome\tposition\tgenotype")
    parsed = parse_23andme("\n".join([*header, text]))
    return {row["rsid"]: row for row in lookup(parsed)}


def test_requested_non_medical_traits_are_allowlisted():
    assert {
        "rs4988235",
        "rs17822931",
        "rs713598",
        "rs1726866",
        "rs10246939",
        "rs10427255",
        "rs1815739",
        "rs72921001",
    } == set(ALLOWLIST)


def test_lookup_returns_interpretation_and_evidence():
    rows = _rows_for(
        "\n".join(
            [
                "rs4988235\t2\t136608646\tAG",
                "rs17822931\t16\t48258198\tTT",
                "rs713598\t7\t141672604\tGC",
                "rs1726866\t7\t141672705\tGA",
                "rs10246939\t7\t141672604\tCT",
                "rs1815739\t11\t66560624\tTT",
                "rs72921001\t11\t6889648\tCA",
            ]
        )
    )

    assert "keeping lactase" in rows["rs4988235"]["interpretation"]
    assert rows["rs17822931"]["interpretation"] == "Associated with dry earwax."
    tas2r38 = rows["rs713598/rs1726866/rs10246939"]
    assert tas2r38["interpretation_status"] == "unresolved_haplotype"
    assert "unphased" in tas2r38["interpretation"]
    assert "common, benign" in rows["rs1815739"]["interpretation"]
    assert "intermediate" in rows["rs72921001"]["interpretation"]
    assert all(row["citation"].startswith("https://") for row in rows.values())
    assert all(row["citations"] for row in rows.values())
    assert all(row["evidence_note"] for row in rows.values())


def test_absent_and_no_call_snps_are_not_interpreted():
    rows = _rows_for("rs4988235\t2\t136608646\t--")

    assert rows["rs4988235"]["measured"] is False
    assert rows["rs4988235"]["interpretation"] == "Not measured on this chip."
    assert rows["rs72921001"]["measured"] is False


def test_unverified_or_unsupported_reference_build_fails_closed():
    missing_build = _rows_for("rs4988235\t2\t136608646\tAG", reference_build=None)
    build_38 = _rows_for("rs4988235\t2\t136608646\tAG", reference_build="38")

    for rows in (missing_build, build_38):
        row = rows["rs4988235"]
        assert row["measured"] is True
        assert row["interpretable"] is False
        assert row["interpretation_status"] == "unverified_reference_build"
        assert "no genotype meaning was assigned" in row["interpretation"]


def test_photic_sneeze_does_not_claim_a_portable_allele_direction():
    interpretations = {
        genotype: _rows_for(f"rs10427255\t2\t72814783\t{genotype}")["rs10427255"]
        for genotype in ("CC", "CT", "TT")
    }

    assert len({row["interpretation"] for row in interpretations.values()}) == 1
    row = interpretations["CC"]
    assert "does not assign a portable genotype direction" in row["interpretation"]
    assert len(row["citations"]) == 2


def test_tas2r38_is_one_combined_haplotype_result_and_fails_closed_when_unresolved():
    pav = _rows_for(
        "\n".join(
            [
                "rs713598\t7\t141672604\tGG",
                "rs1726866\t7\t141672705\tGG",
                "rs10246939\t7\t141672604\tCC",
            ]
        )
    )
    avi = _rows_for(
        "\n".join(
            [
                "rs713598\t7\t141672604\tCC",
                "rs1726866\t7\t141672705\tAA",
                "rs10246939\t7\t141672604\tTT",
            ]
        )
    )
    partial = _rows_for("rs713598\t7\t141672604\tGG")

    composite_id = "rs713598/rs1726866/rs10246939"
    assert pav[composite_id]["interpretation_status"] == "interpreted"
    assert "PAV/PAV" in pav[composite_id]["interpretation"]
    assert avi[composite_id]["interpretation_status"] == "interpreted"
    assert "AVI/AVI" in avi[composite_id]["interpretation"]
    assert partial[composite_id]["interpretation_status"] == "not_fully_measured"
    assert len([key for key in pav if "rs713598" in key]) == 1
