"""End-to-end Flask API tests for the local guided-report path."""

from io import BytesIO
import json

import pytest
from werkzeug.datastructures import MultiDict

from backend.app import MAX_UPLOAD_BYTES, app
from backend.reference_panel import reference_rsids
from backend.traits import ALLOWLIST
from backend.upload_request import InMemoryUploadRequest


VALID_EXPORT = "\n".join(
    [
        "# This data file generated by 23andMe at: 2026-07-11",
        "# We are using reference human assembly build 37.",
        "# rsid\tchromosome\tposition\tgenotype",
        "rs4988235\t2\t136608646\tAG",
        "rs17822931\t16\t48258198\tTT",
        "rs999999999\t1\t12345\tCC",
        "i713426\tY\t726912\t--",
    ]
).encode()


@pytest.fixture()
def client():
    app.config.update(TESTING=True, MAX_CONTENT_LENGTH=MAX_UPLOAD_BYTES)
    with app.test_client() as test_client:
        yield test_client


def _upload(client, content=VALID_EXPORT, filename="genome.txt", **fields):
    data = MultiDict([("file", (BytesIO(content), filename))])
    for key, value in fields.items():
        if isinstance(value, list):
            for item in value:
                data.add(key, item)
        else:
            data.add(key, value)
    return client.post("/api/analyze", data=data)


def test_complete_guided_report_contract_and_privacy(client):
    response = _upload(
        client,
        population_label="Broadly South Asian",
        requested_rsid=["rs4988235", "rs429358"],
    )

    assert response.status_code == 200
    assert response.headers["Cache-Control"] == "no-store, max-age=0"
    assert response.headers["Pragma"] == "no-cache"
    data = response.get_json()
    assert data["filename"] == "genome.txt"
    assert data["vendor"] == "23andMe"
    assert data["reference_build"] == "GRCh37"
    assert data["stats"]["total"] == 4
    assert data["stats"]["called"] == 3
    assert data["retention"] == {
        "mode": "selected",
        "requested_rsids": len(reference_rsids() | set(ALLOWLIST)),
        "retained_rsids": 2,
        "duplicate_conflict_scope": "retained_records",
    }
    assert data["coverage"]["chromosome_counts"] == {
        "1": 1,
        "2": 1,
        "16": 1,
        "Y": 1,
    }
    assert data["population_context"]["canonical_key"] == "south_asian"
    assert data["population_context"]["inferred_from_dna"] is False
    assert data["traits"]["measured_count"] == 2
    assert data["boundaries"]["policy"] == "default-deny"
    assert data["boundaries"]["requested_checks"][1]["rsid"] == "rs429358"
    assert data["boundaries"]["requested_checks"][1]["refused"] is True
    assert data["studies"]["items"]
    assert data["genetic_closeness"]["status"] == "insufficient_overlap"

    serialized = json.dumps(data)
    assert "rs999999999" not in serialized
    assert "726912" not in serialized
    assert "snps" not in data


def test_filename_is_sanitized(client):
    response = _upload(client, filename="../../private genome.txt")

    assert response.status_code == 200
    assert response.get_json()["filename"] == "private_genome.txt"


@pytest.mark.parametrize(
    ("content", "filename", "expected_code"),
    [
        (b"", "empty.txt", "empty_input"),
        (b"rs1\t1\t1\tAA\n", "headerless.txt", "unsupported_vendor"),
        (
            b"# AncestryDNA raw data\n# rsid\tchromosome\tposition\tgenotype\nrs1\t1\t1\tAA\n",
            "other.txt",
            "unsupported_vendor",
        ),
        (b"%PDF\tobject\tstream\tendobj", "fake.txt", "unsupported_vendor"),
        (b"\xff\xfe\xfd", "encoded.txt", "invalid_encoding"),
        (VALID_EXPORT, "archive.zip", "invalid_file_type"),
    ],
)
def test_invalid_uploads_fail_with_stable_json(client, content, filename, expected_code):
    response = _upload(client, content=content, filename=filename)

    assert response.status_code == 400
    assert response.is_json
    assert response.get_json()["code"] == expected_code
    assert response.headers["Cache-Control"] == "no-store, max-age=0"


def test_missing_file_fails_safely(client):
    response = client.post("/api/analyze", data={"population_label": "European"})

    assert response.status_code == 400
    assert response.get_json()["code"] == "missing_file"


def test_oversized_numeric_row_fails_as_safe_json_instead_of_crashing(client):
    content = "\n".join(
        [
            "# This data file generated by 23andMe",
            "# rsid\tchromosome\tposition\tgenotype",
            f"rs1\t1\t{'1' * 5000}\tAA",
        ]
    ).encode()

    response = _upload(client, content=content)

    assert response.status_code == 400
    assert response.get_json()["code"] == "no_valid_records"


def test_oversized_request_uses_json_error(client):
    original_limit = app.config["MAX_CONTENT_LENGTH"]
    app.config["MAX_CONTENT_LENGTH"] = 100
    try:
        response = _upload(client)
    finally:
        app.config["MAX_CONTENT_LENGTH"] = original_limit

    assert response.status_code == 413
    assert response.get_json()["code"] == "file_too_large"


def test_app_uses_the_in_memory_multipart_request_class():
    assert app.request_class is InMemoryUploadRequest
