"""Focused coverage for conservative 23andMe raw-data parsing."""

import pytest

from backend.parser import ParseError, genotype_for, parse_23andme


def export(*rows: str, metadata: tuple[str, ...] = ()) -> str:
    return "\n".join(
        [
            "# This data file generated by 23andMe at: 2026-07-11",
            *metadata,
            "# rsid\tchromosome\tposition\tgenotype",
            *rows,
        ]
    )


SAMPLE = export(
    "rs4988235\t2\t136608646\tAA",
    "rs17822931\t16\t48258198\tCT",
    "rs1234567\t1\t12345\t--",
    "malformed line without tabs",
    metadata=(
        "# We are using reference human assembly build 37 (also known as Annotation Release 104).",
    ),
)


def test_parses_records_and_reports_coverage_metadata():
    result = parse_23andme(SAMPLE, require_vendor_header=True)

    assert result["stats"] == {
        "total": 3,
        "called": 2,
        "no_calls": 1,
        "malformed": 1,
        "duplicates": 0,
        "conflicting_duplicates": 0,
        "input_rows": 4,
    }
    assert result["snps"]["rs4988235"] == {
        "chromosome": "2",
        "position": "136608646",
        "genotype": "AA",
    }
    assert result["coverage"]["call_rate"] == pytest.approx(2 / 3, abs=1e-6)
    assert result["coverage"]["observed_chromosomes"] == ["1", "2", "16"]
    assert result["coverage"]["by_chromosome"]["1"]["no_calls"] == 1
    assert result["reference_build"] == "GRCh37"
    assert result["vendor"] == "23andMe"
    assert result["retention"] == {
        "mode": "all",
        "requested_rsids": None,
        "retained_rsids": 3,
        "duplicate_conflict_scope": "all_records",
    }


def test_comments_blank_lines_bom_case_and_whitespace_are_handled():
    text = "\ufeff\n" + export(
        "RS4988235\t 2 \t 00136608646 \t ag ",
        "",
        "# an ordinary comment",
    )

    result = parse_23andme(text, require_vendor_header=True)

    assert result["snps"]["rs4988235"] == {
        "chromosome": "2",
        "position": "136608646",
        "genotype": "AG",
    }
    assert result["stats"]["input_rows"] == 1


def test_no_calls_are_retained_but_genotype_lookup_returns_none():
    result = parse_23andme(
        export("rs1\t1\t1\t--", "rs2\t2\t2\t-"),
        require_vendor_header=True,
    )

    assert result["stats"]["no_calls"] == 2
    assert genotype_for(result, "rs1") is None
    assert genotype_for(result, "RS2") is None
    assert genotype_for(result, "rs_absent_from_chip") is None


def test_mt_y_haploid_calls_and_indels_are_valid():
    result = parse_23andme(
        export(
            "rs100\tMT\t73\tA",
            "i4000001\tY\t2655180\tG",
            "rs101\tX\t10001\tDI",
            "rs102\t1\t10002\tII",
            "rs103\t2\t10003\tD",
        ),
        require_vendor_header=True,
    )

    assert result["stats"]["called"] == 5
    assert result["coverage"]["observed_chromosomes"] == ["1", "2", "X", "Y", "MT"]
    assert result["coverage"]["by_chromosome"]["MT"]["called"] == 1
    assert result["coverage"]["by_chromosome"]["Y"]["called"] == 1
    assert genotype_for(result, "i4000001") == "G"


@pytest.mark.parametrize(
    "bad_row",
    [
        "not-a-marker\t1\t1\tAA",
        "rs01\t1\t1\tAA",
        "rs2\t23\t2\tCC",
        "rs3\t1\t0\tGG",
        "rs4\t1\t-2\tTT",
        "rs5\t1\tnot-a-position\tAG",
        "rs6\t1\t6\tZZ",
        "rs7\t1\t7\tAAA",
        "rs8 1 8 AC",
        "rs9\t1\t+9\tAC",
        "rs10\t1\t1_000\tAC",
        f"rs{'1' * 5000}\t1\t1\tAC",
        f"rs10\t1\t{'1' * 5000}\tAC",
    ],
)
def test_invalid_rows_are_counted_and_not_retained(bad_row: str):
    result = parse_23andme(
        export("rs1\t1\t1\tAA", bad_row),
        require_vendor_header=True,
    )

    assert result["stats"]["total"] == 1
    assert result["stats"]["malformed"] == 1


def test_duplicate_marker_ids_are_counted_and_first_valid_record_wins():
    result = parse_23andme(
        export(
            "rs1\t1\t100\tAA",
            "rs1\t1\t100\tAA",
            "RS1\t1\t100\tGG",
        ),
        require_vendor_header=True,
    )

    assert result["stats"]["total"] == 1
    assert result["stats"]["duplicates"] == 2
    assert result["stats"]["conflicting_duplicates"] == 1
    assert genotype_for(result, "rs1") == "AA"


def test_selected_retention_keeps_only_requested_records_but_counts_everything():
    text = export(
        "rs1\t1\t100\tAA",
        "rs2\tY\t200\t--",
        "rs3\tMT\t300\tG",
        "not-a-valid-row",
    )

    full = parse_23andme(text, require_vendor_header=True)
    selected = parse_23andme(
        text,
        require_vendor_header=True,
        retain_rsids={"RS1", "rs999"},
    )

    assert selected["snps"] == {"rs1": full["snps"]["rs1"]}
    assert selected["stats"] == full["stats"]
    assert selected["coverage"] == full["coverage"]
    assert genotype_for(selected, "rs1") == "AA"
    assert genotype_for(selected, "rs3") is None
    assert selected["retention"] == {
        "mode": "selected",
        "requested_rsids": 2,
        "retained_rsids": 1,
        "duplicate_conflict_scope": "retained_records",
    }


def test_empty_retention_filter_still_validates_and_reports_full_coverage():
    result = parse_23andme(
        export("rs1\t1\t1\tAA", "rs2\tMT\t2\t--"),
        require_vendor_header=True,
        retain_rsids=(),
    )

    assert result["snps"] == {}
    assert result["stats"]["total"] == 2
    assert result["stats"]["called"] == 1
    assert result["coverage"]["by_chromosome"]["MT"]["no_calls"] == 1
    assert result["retention"]["requested_rsids"] == 0


def test_selected_mode_counts_all_duplicates_but_scopes_conflicts_to_retained_ids():
    result = parse_23andme(
        export(
            "rs1\t1\t100\tAA",
            "rs1\t1\t100\tGG",  # retained conflict: detectable
            "rs2\t2\t200\tCC",
            "rs2\t2\t201\tTT",  # unretained conflict: payload not stored
        ),
        require_vendor_header=True,
        retain_rsids={"rs1"},
    )

    assert result["stats"]["total"] == 2
    assert result["stats"]["duplicates"] == 2
    assert result["stats"]["conflicting_duplicates"] == 1
    assert result["coverage"]["by_chromosome"] == {
        "1": {"total": 1, "called": 1, "no_calls": 0},
        "2": {"total": 1, "called": 1, "no_calls": 0},
    }
    assert result["snps"]["rs1"]["genotype"] == "AA"
    assert result["retention"]["duplicate_conflict_scope"] == "retained_records"


def test_retain_rsids_rejects_a_single_string_to_prevent_character_iteration():
    with pytest.raises(TypeError, match="iterable of marker IDs"):
        parse_23andme(export("rs1\t1\t1\tAA"), retain_rsids="rs1")


def test_headerless_fixture_is_unknown_in_compatibility_mode():
    result = parse_23andme("rs4988235\t2\t136608646\tAG")

    assert result["vendor"] == "unknown"
    assert genotype_for(result, "rs4988235") == "AG"


def test_strict_mode_rejects_headerless_or_unverified_input():
    with pytest.raises(ParseError) as caught:
        parse_23andme(
            "rs4988235\t2\t136608646\tAG",
            require_vendor_header=True,
        )

    assert caught.value.code == "unsupported_vendor"
    assert caught.value.to_dict()["code"] == "unsupported_vendor"


def test_explicit_other_vendor_is_rejected_even_in_compatibility_mode():
    text = "\n".join(
        [
            "# AncestryDNA raw data download",
            "# rsid\tchromosome\tposition\tgenotype",
            "rs4988235\t2\t136608646\tAG",
        ]
    )

    with pytest.raises(ParseError, match="another DNA service") as caught:
        parse_23andme(text)

    assert caught.value.code == "unsupported_vendor"


def test_conflicting_vendor_signatures_are_rejected():
    text = "\n".join(
        [
            "# This data file generated by 23andMe",
            "# Imported from an AncestryDNA raw data download",
            "# rsid\tchromosome\tposition\tgenotype",
            "rs4988235\t2\t136608646\tAG",
        ]
    )

    with pytest.raises(ParseError) as caught:
        parse_23andme(text, require_vendor_header=True)

    assert caught.value.code == "unsupported_vendor"


def test_verified_vendor_requires_canonical_column_header():
    text = "\n".join(
        [
            "# This data file generated by 23andMe",
            "rs4988235\t2\t136608646\tAG",
        ]
    )

    with pytest.raises(ParseError) as caught:
        parse_23andme(text, require_vendor_header=True)

    assert caught.value.code == "invalid_header"


def test_current_23andme_is_generated_header_is_verified():
    text = "\n".join(
        [
            "# This data file is generated by 23andMe.",
            "# We are using reference human assembly build 37.",
            "# rsid chromosome position genotype",
            "rs1\t1\t1\tAA",
        ]
    )
    result = parse_23andme(text, require_vendor_header=True)
    assert result["vendor"] == "23andMe"
    assert result["reference_build"] == "GRCh37"


@pytest.mark.parametrize("text", ["", " \n\t", "\ufeff"])
def test_empty_input_has_a_stable_api_error(text: str):
    with pytest.raises(ParseError) as caught:
        parse_23andme(text)

    assert caught.value.code == "empty_input"
    assert caught.value.to_dict() == {
        "error": "The uploaded genotype file is empty.",
        "code": "empty_input",
    }


def test_comments_only_or_arbitrary_tsv_has_no_valid_records():
    for text in (
        "# synthetic notes only",
        "%PDF-1.7\tobject\tstream\tendobj",
    ):
        with pytest.raises(ParseError) as caught:
            parse_23andme(text)

        assert caught.value.code == "no_valid_records"
        assert "input_rows" in caught.value.to_dict()["details"]


@pytest.mark.parametrize("version", ["v3", "v4", "v5"])
def test_chip_version_is_used_only_when_explicitly_declared(version: str):
    result = parse_23andme(
        export("rs1\t1\t1\tAA", metadata=(f"# Genotyping chip version: {version}",)),
        require_vendor_header=True,
    )

    assert result["chip_version"] == version


def test_chip_version_is_not_guessed_from_marker_count_or_conflicting_metadata():
    ordinary = parse_23andme(export("rs1\t1\t1\tAA"), require_vendor_header=True)
    conflicting = parse_23andme(
        export(
            "rs1\t1\t1\tAA",
            metadata=("# chip version: v4", "# array platform v5"),
        ),
        require_vendor_header=True,
    )

    assert ordinary["chip_version"] is None
    assert conflicting["chip_version"] is None


def test_conflicting_or_absent_reference_build_is_not_guessed():
    absent = parse_23andme(export("rs1\t1\t1\tAA"), require_vendor_header=True)
    conflicting = parse_23andme(
        export(
            "rs1\t1\t1\tAA",
            metadata=("# reference genome GRCh37", "# lifted over to GRCh38"),
        ),
        require_vendor_header=True,
    )

    assert absent["reference_build"] is None
    assert conflicting["reference_build"] is None
