"""Core parser tests. Run: python -m pytest -q

TODO(P1): add cases against a real PGP sample file (data/samples/), and for
v3/v4/v5 chip detection, MT/Y rows, and non-23andMe vendor detection.
"""
from backend.parser import genotype_for, parse_23andme

SAMPLE = "\n".join(
    [
        "# This data file generated by 23andMe",
        "# rsid\tchromosome\tposition\tgenotype",
        "rs4988235\t2\t136608646\tAA",
        "rs17822931\t16\t48258198\tCT",
        "rs1234567\t1\t12345\t--",  # no-call
        "malformed line without tabs",  # should be counted, not crash
    ]
)


def test_parses_snps_and_skips_header():
    result = parse_23andme(SAMPLE)
    assert result["stats"]["total"] == 3
    assert result["snps"]["rs4988235"]["genotype"] == "AA"
    assert result["vendor"] == "23andMe"


def test_counts_no_calls():
    result = parse_23andme(SAMPLE)
    assert result["stats"]["no_calls"] == 1


def test_counts_malformed_without_crashing():
    result = parse_23andme(SAMPLE)
    assert result["stats"]["malformed"] == 1


def test_genotype_for_missing_rsid_is_none():
    result = parse_23andme(SAMPLE)
    assert genotype_for(result, "rs_absent_from_chip") is None


def test_genotype_for_no_call_is_none():
    result = parse_23andme(SAMPLE)
    assert genotype_for(result, "rs1234567") is None
