"""Integration tests for the deterministic, service-independent report."""

import json

from backend.parser import parse_23andme
from backend.report import build_guided_report


SAMPLE = "\n".join(
    [
        "# This data file generated by 23andMe at: 2026-07-11",
        "# We are using reference human assembly build 37.",
        "# rsid\tchromosome\tposition\tgenotype",
        "rs4988235\t2\t136608646\tAG",
        "rs17822931\t16\t48258198\tTT",
        "rs999999999\t1\t12345\tCC",
    ]
)


def test_guided_report_is_deterministic_and_complete():
    parsed = parse_23andme(SAMPLE)

    first = build_guided_report(
        parsed,
        "Broadly South Asian",
        requested_rsids=["rs4988235", "rs429358"],
    )
    second = build_guided_report(
        parsed,
        "Broadly South Asian",
        requested_rsids=["rs4988235", "rs429358"],
    )

    assert first == second
    assert first["report_version"] == "1.0"
    assert first["population_context"]["canonical_key"] == "south_asian"
    assert first["population_context"]["inferred_from_dna"] is False
    assert first["traits"]["measured_count"] == 2
    assert first["traits"]["unavailable_count"] == 4
    assert first["boundaries"]["policy"] == "default-deny"
    assert first["boundaries"]["requested_checks"] == [
        {"rsid": "rs4988235", "allowed": True, "refused": False, "reason": None},
        {
            "rsid": "rs429358",
            "allowed": False,
            "refused": True,
            "reason": (
                "This marker is outside this report's small, vetted non-medical "
                "trait allowlist, so it will not be interpreted."
            ),
        },
    ]
    assert len(first["boundaries"]["honesty"]) == 3
    assert first["studies"]["curated_as_of"] == "2026-07-11"
    assert first["studies"]["items"]


def test_report_does_not_return_the_raw_genome_or_unknown_markers():
    report = build_guided_report(parse_23andme(SAMPLE), None)
    serialized = json.dumps(report)

    assert "snps" not in report
    assert "rs999999999" not in serialized
    assert "136608646" not in serialized
    assert report["population_context"]["source"] == "not_supplied"
